### ISSUE TITLE
Error: Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by jeremycherfas** [aaronpk/Compass#50]
Suddenly, about 10 days ago, I started getting this error when trying to access my database: Whoops, looks like something went wrong.

That's all I can see.

Error log shows:
```
[Sat Dec 31 06:34:58.604186 2022] [:error] [pid 77843:tid 140111362651904] [client 34.124.232.135:63961] [client 34.124.232.135] ModSecurity: Access denied with code 418 (phase 2). Matched phrase "curl" at ARGS:l. [file "/dh/apache2/template/etc/mod_sec2/99_dreamhost_rules.conf"] [line "133"] [id "1990070"] [msg "Common known arguments for backdoor shell present in ARGS:l"] [hostname "www.compass.jeremycherfas.net"] [uri "/wp-plain.php"] [unique_id "Y7BIkj2g0wAQFF8XGhPWnwAAABI"], referer: www.google.com
[Sat Dec 31 07:52:20.914283 2022] [:error] [pid 83878:tid 140111287150336] [client 34.124.232.135:62246] [client 34.124.232.135] ModSecurity: Access denied with code 418 (phase 2). Matched phrase "curl" at ARGS:l. [file "/dh/apache2/template/etc/mod_sec2/99_dreamhost_rules.conf"] [line "133"] [id "1990070"] [msg "Common known arguments for backdoor shell present in ARGS:l"] [hostname "www.compass.jeremycherfas.net"] [uri "/wp-plain.php"] [unique_id "Y7BatLdVOtUXFx5ZHqbJ2QAAABM"], referer: www.google.com
```

I'm guessing this may be something new that Dreamhost has instituted, and I am wondering if there is a workaround.

I have asked Dreamhost too.

Thanks

Jeremy

**Comment by aaronpk** [comment]
I don't think these entries from the log are relevant, I think that's from Dreamhost blocking bots trying to test if this is a wordpress site, given the `[uri "/wp-plain.php"]` and `[google.com](referer: www.google.com)` in the log.

Can you check the actual Compass log? It should be at `storage/logs/lumen.log`

**Comment by jeremycherfas** [comment]
Of course, you are right.

The Compass log shows `Next ErrorException: DateTimeZone::__construct(): Unknown or bad timezone (Washington DC ) (View: /home/jeremygrav/compass.jeremycherfas.net/resources/views/map.blade.php) in /home/jeremygrav/compass.jeremycherfas.net/storage/framework/views/736cd41ed1eb59bee419f21e934c28c3:36`

And that makes perfect sense, as I was in Washington until today. But I have no recollection of changing the timezone anywhere in Overland or Compass.

The server where Compass is running is on PST.  I changed the iPhone's date/time but that is now back where it started.

Do you need the whole Stack trace?

**Comment by aaronpk** [comment]
oh that's very weird, that shouldn't be happening. I'll push a fix shortly.

**Comment by jeremycherfas** [comment]
OK, great. No rush for me.

**Comment by jeremycherfas** [comment]
Further to this, I am still getting the same error, and it would now be good to be able to access Compass again, if possible.

Stack trace
````Next ErrorException: DateTimeZone::__construct(): Unknown or bad timezone (Washington DC ) (View: /home/jeremygrav/compass.jeremycherfas.net/resources/views/map.blade.php) in /home/jeremygrav/compass.jeremycherfas.net/storage/framework/views/736cd41ed1eb59bee419f21e934c28c3:36  
Stack trace:  
#0 /home/jeremygrav/compass.jeremycherfas.net/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Exception), 0)  
#1 /home/jeremygrav/compass.jeremycherfas.net/vendor/illuminate/view/Engines/CompilerEngine.php(58): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/jeremygra...', Array)  
#2 /home/jeremygrav/compass.jeremycherfas.net/vendor/illuminate/view/View.php(135): Illuminate\View\Engines\CompilerEngine->get('/home/jeremygra...', Array)  
#3 /home/jeremygrav/compass.jeremycherfas.net/vendor/illuminate/view/View.php(106): Illuminate\View\View->getContents()  
#4 /home/jeremygrav/compass.jeremycherfas.net/vendor/illuminate/view/View.php(80): Illuminate\View\View->renderContents()  
#5 /home/jeremygrav/compass.jeremycherfas.net/vendor/illuminate/http/Response.php(51): Illuminate\View\View->render()  
#6 /home/jeremygrav/compass.jeremycherfas.net/vendor/symfony/http-foundation/Response.php(198): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))  
#7 /home/jeremygrav/compass.jeremycherfas.net/vendor/laravel/lumen-framework/src/Application.php(1454): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))  
#8 /home/jeremygrav/compass.jeremycherfas.net/vendor/laravel/lumen-framework/src/Application.php(1399): Laravel\Lumen\Application->prepareResponse(Object(Illuminate\View\View))  
#9 /home/jeremygrav/compass.jeremycherfas.net/vendor/laravel/lumen-framework/src/Application.php(1363): Laravel\Lumen\Application->callControllerCallable(Array, Array)  
#10 /home/jeremygrav/compass.jeremycherfas.net/vendor/laravel/lumen-framework/src/Application.php(1335): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\Controller), 'map', Array)  
#11 /home/jeremygrav/compass.jeremycherfas.net/vendor/laravel/lumen-framework/src/Application.php(1303): Laravel\Lumen\Application->callControllerAction(Array)
#12 /home/jeremygrav/compass.jeremycherfas.net/vendor/laravel/lumen-framework/src/Application.php(1288): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#13 /home/jeremygrav/compass.jeremycherfas.net/vendor/laravel/lumen-framework/src/Application.php(1262): Laravel\Lumen\Application->handleFoundRoute(Array)
#14 /home/jeremygrav/compass.jeremycherfas.net/vendor/laravel/lumen-framework/src/Application.php(1211): Laravel\Lumen\Application->handleDispatcherResponse(Array)
#15 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}(Object(Illuminate\Http\Request))
#16 /home/jeremygrav/compass.jeremycherfas.net/vendor/illuminate/pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#17 /home/jeremygrav/compass.jeremycherfas.net/vendor/illuminate/session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /home/jeremygrav/compass.jeremycherfas.net/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#20 /home/jeremygrav/compass.jeremycherfas.net/vendor/illuminate/cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /home/jeremygrav/compass.jeremycherfas.net/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#23 /home/jeremygrav/compass.jeremycherfas.net/vendor/illuminate/cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /home/jeremygrav/compass.jeremycherfas.net/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#26 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /home/jeremygrav/compass.jeremycherfas.net/vendor/illuminate/pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 /home/jeremygrav/compass.jeremycherfas.net/vendor/laravel/lumen-framework/src/Application.php(1439): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#29 /home/jeremygrav/compass.jeremycherfas.net/vendor/laravel/lumen-framework/src/Application.php(1213): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#30 /home/jeremygrav/compass.jeremycherfas.net/vendor/laravel/lumen-framework/src/Application.php(1153): Laravel\Lumen\Application->dispatch(NULL)
#31 /home/jeremygrav/compass.jeremycherfas.net/public/index.php(28): Laravel\Lumen\Application->run()
#32 {main}  ````

**Comment by jeremycherfas** [comment]
Setting any timezone appears to be the problem. Without a timezone set, the Map displays fine and I can access the other settings when needed.

**Comment by aaronpk** [comment]
Only timezone names like "America/Los_Angeles" and "Europe/Berlin" are supported. I just pushed a fix that will stop erroring out if an invalid timezone is entered in the database.
